export const SocialCauses = {
  SOCIAL: 'SOCIAL',
  POVERTY: 'POVERTY',
  HOMELESSNESS: 'HOMELESSNESS',
  HUNGER: 'HUNGER',
  HEALTH: 'HEALTH',
  SUBSTANCE_ABUSE: 'SUBSTANCE_ABUSE',
  MENTAL: 'MENTAL',
  BULLYING: 'BULLYING',
  SECURITY: 'SECURITY',
  EDUCATION: 'EDUCATION',
  GENDER_EQUALITY: 'GENDER_EQUALITY',
  GENDER_BASED_VIOLENCE: 'GENDER_BASED_VIOLENCE',
  SEXUAL_VIOLENCE: 'SEXUAL_VIOLENCE',
  DOMESTIC_VIOLENCE: 'DOMESTIC_VIOLENCE',
  WATER_SANITATION: 'WATER_SANITATION',
  SUSTAINABLE_ENERGY: 'SUSTAINABLE_ENERGY',
  DECENT_WORK: 'DECENT_WORK',
  INEQUALITY: 'INEQUALITY',
  MINORITY: 'MINORITY',
  MULTICULTURALISM: 'MULTICULTURALISM',
  DIVERSITY_INCLUSION: 'DIVERSITY_INCLUSION',
  INDIGENOUS_PEOPLES: 'INDIGENOUS_PEOPLES',
  DISABILITY: 'DISABILITY',
  LGBTQI: 'LGBTQI',
  REFUGEE: 'REFUGEE',
  MIGRANTS: 'MIGRANTS',
  ORPHANS: 'ORPHANS',
  CHILD_PROTECTION: 'CHILD_PROTECTION',
  COMMUNITY_DEVELOPMENT: 'COMMUNITY_DEVELOPMENT',
  DEPOPULATION: 'DEPOPULATION',
  OVERPOPULATION: 'OVERPOPULATION',
  HUMAN_RIGHTS: 'HUMAN_RIGHTS',
  SUSTAINABILITY: 'SUSTAINABILITY',
  RESPONSIBLE_CONSUMPTION: 'RESPONSIBLE_CONSUMPTION',
  CLIMATE_CHANGE: 'CLIMATE_CHANGE',
  NATURAL_DISASTERS: 'NATURAL_DISASTERS',
  BIODIVERSITY: 'BIODIVERSITY',
  ANIMAL_RIGHTS: 'ANIMAL_RIGHTS',
  ARMED_CONFLICT: 'ARMED_CONFLICT',
  PEACEBUILDING: 'PEACEBUILDING',
  DEMOCRACY: 'DEMOCRACY',
  CIVIC_ENGAGEMENT: 'CIVIC_ENGAGEMENT',
  JUSTICE: 'JUSTICE',
  GOVERNANCE: 'GOVERNANCE',
  CRIME_PREVENTION: 'CRIME_PREVENTION',
  CORRUPTION: 'CORRUPTION',
  OTHER: 'OTHER',
  RURAL_DEVELOPMENT: 'RURAL_DEVELOPMENT',
  VEGANISM: 'VEGANISM',
  BLACK_LIVES_MATTER: 'BLACK_LIVES_MATTER',
  ISLAMOPHOBIA: 'ISLAMOPHOBIA',
  ANTI_SEMITISM: 'ANTI_SEMITISM',
};

export const ApplicantStatus = {
  PENDING: 'PENDING',
  OFFERED: 'OFFERED',
  REJECTED: 'REJECTED',
  WITHRAWN: 'WITHDRAWN',
  APPROVED: 'APPROVED',
  HIRED: 'HIRED',
};

export const UserStatusType = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPEND: 'SUSPEND',
};

export const ProjectLengthType = {
  LESS_THAN_A_DAY: 'LESS_THAN_A_DAY',
  LESS_THAN_A_MONTH: 'LESS_THAN_A_MONTH',
  ONE_THREE_MONTHS: '1_3_MONTHS',
  THREE_SIX_MONTHS: '3_6_MONTHS',
  SIX_MONTHS_OR_MORE: '6_MONTHS_OR_MORE',
};

export const ProjectType = {
  ONE_OFF: 'ONE_OFF',
  PART_TIME: 'PART_TIME',
  FULL_TIME: 'FULL_TIME',
};

export const ProjectRemotePreferenceType = {
  ONSITE: 'ONSITE',
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
};

export const ProjectStatusType = {
  DRAFT: 'DRAFT',
  EXPIRE: 'EXPIRE',
  ACTIVE: 'ACTIVE',
};

export const ProjectPaymentType = {
  VOLUNTEER: 'VOLUNTEER',
  PAID: 'PAID',
};

export const ProjectPaymentSchemeType = {
  HOURLY: 'HOURLY',
  FIXED: 'FIXED',
};

export const OrganizationType = {
  SOCIAL: 'SOCIAL',
  NONPROFIT: 'NONPROFIT',
  COOP: 'COOP',
  IIF: 'IIF',
  PUBLIC: 'PUBLIC',
  INTERGOV: 'INTERGOV',
  DEPARTMENT: 'DEPARTMENT',
  OTHER: 'OTHER',
};

export const NotificationType = {
  FOLLOWED: 'FOLLOWED',
  COMMENT_LIKE: 'COMMENT_LIKE',
  POST_LIKE: 'POST_LIKE',
  CHAT: 'CHAT',
  SHARE_POST: 'SHARE_POST',
  SHARE_PROJECT: 'SHARE_PROJECT',
  COMMENT: 'COMMENT',
  APPLICATION: 'APPLICATION',
  OFFER: 'OFFER',
  REJECT: 'REJECT',
  APPROVED: 'APPROVED',
  HIRED: 'HIRED',
  PROJECT_COMPLETE: 'PROJECT_COMPLETE',
  EMPLOYEE_CANCELED: 'EMPLOYEE_CANCELED',
  EMPLOYER_CANCELED: 'EMPLOYER_CANCELED',
  EMPLOYER_CONFIRMED: 'EMPLOYER_CONFIRMED',
};

export const NotificationTitle = {
  FOLLOWED: 'Followed',
  COMMENT_LIKE: 'Comment liked',
  POST_LIKE: 'Post liked',
  CHAT: 'New Message',
  SHARE_POST: 'Post shared',
  SHARE_PROJECT: 'Project shared',
  COMMENT: 'New commented',
  APPLICATION: 'Project applied',
  OFFER: 'Have an offer',
  REJECT: 'Rejected',
  APPROVED: 'Offer approved',
  HIRED: 'Hired',
  PROJECT_COMPLETE: 'Project complete',
  EMPLOYEE_CANCELED: 'Employee canceled project',
  EMPLOYER_CANCELED: 'Employer removed you from project',
  EMPLOYER_CONFIRMED: 'Employer confirmed your work',
};

export const IdentityType = {
  ORG: 'organizations',
  USER: 'users',
};

export const ChatType = {
  CHAT: 'CHAT',
  GROUPED: 'GROUPED',
  CHANNEL: 'CHANNEL',
};

export const ChatMemberType = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
};

export const SearchType = {
  POSTS: 'posts',
  USERS: 'users',
  RELATED_USERS: 'related_users',
  PROJECTS: 'projects',
  CHATS: 'chats',
  ORGANIZATIONS: 'organizations',
};

export const MediaContentType = {
  JPEG: 'image/jpeg',
  PNG: 'image/png',
  PDF: 'application/pdf',
};

export const PaymentCurrency = {
  USD: 'USD',
  JPY: 'JPY',
  EUR: 'EUR',
};

export const PaymentService = {
  STRIPE: 'STRIPE',
};

export const Languages = {
  AA: 'Afar',
  AB: 'Abkhazian',
  AE: 'Avestan',
  AF: 'Afrikaans',
  AK: 'Akan',
  AM: 'Amharic',
  AN: 'Aragonese',
  AR: 'Arabic',
  AS: 'Assamese',
  AV: 'Avaric',
  AY: 'Aymara',
  AZ: 'Azerbaijani',
  BA: 'Bashkir',
  BE: 'Belarusian',
  BG: 'Bulgarian',
  BH: 'Bihari languages',
  BI: 'Bislama',
  BM: 'Bambara',
  BN: 'Bengali',
  BO: 'Tibetan',
  BR: 'Breton',
  BS: 'Bosnian',
  CA: 'Catalan',
  CE: 'Chechen',
  CH: 'Chamorro',
  CO: 'Corsican',
  CR: 'Cree',
  CS: 'Czech',
  CU: 'Church Slavic',
  CV: 'Chuvash',
  CY: 'Welsh',
  DA: 'Danish',
  DE: 'German',
  DV: 'Maldivian',
  DZ: 'Dzongkha',
  EE: 'Ewe',
  EL: 'Greek',
  EN: 'English',
  EO: 'Esperanto',
  ES: 'Spanish',
  ET: 'Estonian',
  EU: 'Basque',
  FA: 'Persian',
  FF: 'Fulah',
  FI: 'Finnish',
  FJ: 'Fijian',
  FO: 'Faroese',
  FR: 'French',
  FY: 'Western Frisian',
  GA: 'Irish',
  GD: 'Gaelic',
  GL: 'Galician',
  GN: 'Guarani',
  GU: 'Gujarati',
  GV: 'Manx',
  HA: 'Hausa',
  HE: 'Hebrew',
  HI: 'Hindi',
  HO: 'Hiri Motu',
  HR: 'Croatian',
  HT: 'Haitian',
  HU: 'Hungarian',
  HY: 'Armenian',
  HZ: 'Herero',
  IA: 'Interlingua',
  ID: 'Indonesian',
  IE: 'Interlingue',
  IG: 'Igbo',
  II: 'Sichuan Yi',
  IK: 'Inupiaq',
  IO: 'Ido',
  IS: 'Icelandic',
  IT: 'Italian',
  IU: 'Inuktitut',
  JA: 'Japanese',
  JV: 'Javanese',
  KA: 'Georgian',
  KG: 'Kongo',
  KI: 'Kikuyu',
  KJ: 'Kuanyama',
  KK: 'Kazakh',
  KL: 'Kalaallisut',
  KM: 'Central Khmer',
  KN: 'Kannada',
  KO: 'Korean',
  KR: 'Kanuri',
  KS: 'Kashmiri',
  KU: 'Kurdish',
  KV: 'Komi',
  KW: 'Cornish',
  KY: 'Kirghiz',
  LA: 'Latin',
  LB: 'Luxembourgish',
  LG: 'Ganda',
  LI: 'Limburgan',
  LN: 'Lingala',
  LO: 'Lao',
  LT: 'Lithuanian',
  LU: 'Luba-Katanga',
  LV: 'Latvian',
  MG: 'Malagasy',
  MH: 'Marshallese',
  MI: 'Maori',
  MK: 'Macedonian',
  ML: 'Malayalam',
  MN: 'Mongolian',
  MR: 'Marathi',
  MS: 'Malay',
  MT: 'Maltese',
  MY: 'Burmese',
  NA: 'Nauru',
  NB: 'Norwegian',
  ND: 'North Ndebele',
  NE: 'Nepali',
  NG: 'Ndonga',
  NL: 'Dutch',
  NN: 'Norwegian',
  NO: 'Norwegian',
  NR: 'South Ndebele',
  NV: 'Navajo',
  NY: 'Chichewa',
  OC: 'Occitan',
  OJ: 'Ojibwa',
  OM: 'Oromo',
  OR: 'Oriya',
  OS: 'Ossetic',
  PA: 'Panjabi',
  PI: 'Pali',
  PL: 'Polish',
  PS: 'Pushto',
  PT: 'Portuguese',
  QU: 'Quechua',
  RM: 'Romansh',
  RN: 'Rundi',
  RO: 'Romanian',
  RU: 'Russian',
  RW: 'Kinyarwanda',
  SA: 'Sanskrit',
  SC: 'Sardinian',
  SD: 'Sindhi',
  SE: 'Northern Sami',
  SG: 'Sango',
  SI: 'Sinhala',
  SK: 'Slovak',
  SL: 'Slovenian',
  SM: 'Samoan',
  SN: 'Shona',
  SO: 'Somali',
  SQ: 'Albanian',
  SR: 'Serbian',
  SS: 'Swati',
  ST: 'Sotho, Southern',
  SU: 'Sundanese',
  SV: 'Swedish',
  SW: 'Swahili',
  TA: 'Tamil',
  TE: 'Telugu',
  TG: 'Tajik',
  TH: 'Thai',
  TI: 'Tigrinya',
  TK: 'Turkmen',
  TL: 'Tagalog',
  TN: 'Tswana',
  TO: 'Tonga',
  TR: 'Turkish',
  TS: 'Tsonga',
  TT: 'Tatar',
  TW: 'Twi',
  TY: 'Tahitian',
  UG: 'Uighur',
  UK: 'Ukrainian',
  UR: 'Urdu',
  UZ: 'Uzbek',
  VE: 'Venda',
  VI: 'Vietnamese',
  VO: 'Volapük',
  WA: 'Walloon',
  WO: 'Wolof',
  XH: 'Xhosa',
  YI: 'Yiddish',
  YO: 'Yoruba',
  ZA: 'Zhuang',
  ZH: 'Chinese',
  ZU: 'Zulu',
};

export const LanguageLvel = {
  BASIC: 'BASIC',
  CONVERSANT: 'CONVERSANT',
  PROFICIENT: 'PROFICIENT',
  FLUENT: 'FLUENT',
  NATIVE: 'NATIVE',
};
